changelog:
  exclude:
    labels:
      - exclude-from-release
  categories:
    - title: New features and enhancements
      labels:
        - feature
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Breaking Changes
      labels:
        - 'breaking change'
    - title: Other Changes
      labels:
        - "*"
