language: python
os: linux
dist: xenial

python:
   - 3.5
   - 3.6
   - 3.7
   - 3.8
   - 3.9
env:
   - CLICK=7
   - CLICK=8

install:
   - pip install tox-travis

script: tox

# Only py38-click7 runs pytest with coverage and send results to codecov
after_success: |
   if [[ $TRAVIS_PYTHON_VERSION =~ ^3.8 && $CLICK == 7 ]]; then
      pip install codecov
      codecov
   fi

jobs:
   exclude:
      - { python: 3.5, env: CLICK=8 }  # Click 8.0 doesn't support Python 3.5
   include:
      - { python: 3.8, env: TOXENV=lint }
      - { python: 3.8, env: TOXENV=mypy }
      - { python: 3.8, env: TOXENV=twine }
      - { python: 3.8, env: TOXENV=docs }
